# -*- coding: utf-8 -*-
"""Protein4_CleanUI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zioXJwAsDw_4oKI6gQC7K27F-1Fr-91Y
"""

#@title 🧬 Protein Expression Severity Predictor

# Choose your input values:
fish_species = "Common Carp"  #@param ["Common Carp", "F2", "F3", "F4", "F5"]
organ = "Gill"  #@param ["Gill", "Kidney", "Liver", "O2", "O3"]
disease = "Koi"  #@param ["Koi", "D2", "D3", "D4", "D5"]
gene = "G1"  #@param ["G1", "G2", "G3", "G4", "G5"]

submit = True  #@param {type:"boolean"}

if submit:
    print("🔬 Analyzing prediction...")
")
    if fish_species == "Common Carp" and organ == "Gill" and disease == "Koi":
        severity = "High"
    else:
        severity = "Moderate"

    print(f"✅ Predicted Severity for {disease} in {organ} of {fish_species} is: {severity}")
